In [5]:
import pandas as pd
cases = pd.read_csv("covid_confirmed_usafacts.csv")
deaths = pd.read_csv("covid_deaths_usafacts.csv")
county = pd.read_csv("covid_county_population_usafacts.csv")
cases

,countyFIPS,County Name,State,StateFIPS,2020-01-22,2020-01-23,2020-01-24,2020-01-25,2020-01-26,2020-01-27,...,2023-01-07,2023-01-08,2023-01-09,2023-01-10,2023-01-11,2023-01-12,2023-01-13,2023-01-14,2023-01-15,2023-01-16
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,19205,19205,19205,19205,19205,19318,19318,19318,19318,19318
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,68182,68182,68182,68182,68182,68518,68518,68518,68518,68518
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,7120,7120,7120,7120,7120,7188,7188,7188,7188,7188
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,7808,7808,7808,7808,7808,7855,7855,7855,7855,7855
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,12394,12394,12430,12430,12430,12437,12437,12437,12437,12437
3189,56039,Teton County,WY,56,0,0,0,0,0,0,...,11997,11997,12035,12035,12035,12045,12045,12045,12045,12045
3190,56041,Uinta County,WY,56,0,0,0,0,0,0,...,6303,6303,6318,6318,6318,6333,6333,6333,6333,6333
3191,56043,Washakie County,WY,56,0,0,0,0,0,0,...,2717,2717,2727,2727,2727,2731,2731,2731,2731,2731
3192,56045,Weston County,WY,56,0,0,0,0,0,0,...,1876,1876,1880,1880,1880,1881,1881,1881,1881,1881

In [6]:
deaths

,countyFIPS,County Name,State,StateFIPS,2020-01-22,2020-01-23,2020-01-24,2020-01-25,2020-01-26,2020-01-27,...,2023-01-07,2023-01-08,2023-01-09,2023-01-10,2023-01-11,2023-01-12,2023-01-13,2023-01-14,2023-01-15,2023-01-16
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,230,230,230,230,230,230,230,230,230,230
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,719,719,719,719,719,721,721,721,721,721
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,103,103,103,103,103,103,103,103,103,103
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,108,108,108,108,108,108,108,108,108,108
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,136,136,136,136,136,136,136,136,136,136
3189,56039,Teton County,WY,56,0,0,0,0,0,0,...,16,16,16,16,16,16,16,16,16,16
3190,56041,Uinta County,WY,56,0,0,0,0,0,0,...,43,43,43,43,43,43,43,43,43,43
3191,56043,Washakie County,WY,56,0,0,0,0,0,0,...,47,47,47,47,47,47,47,47,47,47
3192,56045,Weston County,WY,56,0,0,0,0,0,0,...,22,22,22,22,22,22,22,22,22,22

In [7]:
county

      countyFIPS            County Name State  population
0              0  Statewide Unallocated    AL           0
1           1001         Autauga County    AL       55869
2           1003         Baldwin County    AL      223234
3           1005         Barbour County    AL       24686
4           1007            Bibb County    AL       22394
...          ...                    ...   ...         ...
3190       56037      Sweetwater County    WY       42343
3191       56039           Teton County    WY       23464
3192       56041           Uinta County    WY       20226
3193       56043        Washakie County    WY        7805
3194       56045          Weston County    WY        6927

[3195 rows x 4 columns]

In [ ]:
result = pd.concat([df1, df4], axis=1)